version: '2'
services: 
  sonarqube:
    image: sonarqube:latest
    environment:
      SONARQUBE_JDBC_USERNAME: root 
      SONARQUBE_JDBC_PASSWORD: root 
      SONARQUBE_JDBC_URL: jdbc:mysql://db/sonar?useUnicode=true&characterEncoding=utf8
    restart: always
    ports:
      - 10012:9000 
      - 10013:9092 
  db:
    image: mysql:5.6
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root' 
      MYSQL_DATABASE: 'sonar'