version: '2'
services:
  geth:
    image: geth
    ports:
      # 8545 TCP, used by the HTTP based JSON RPC API
      # 8546 TCP, used by the WebSocket based JSON RPC API
      # 30303 TCP and UDP, used by the P2P protocol running the network
      # 30304 UDP, used by the P2P protocol's new peer discovery overlay
      - 8545:8545
      - 8546:8546
      - 30303:30303
      - 30304:30304
    container_name: geth
    volumes:
      - ./init:/init
    command: "/geth init /init.json && bootnode --genkey=boot.key &&  bootnode --nodekey=boot.key && /geth --datadir=/data"