version: '3.1'

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vegetables
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 33060:3306
