version: '2'
services: 
  mysql:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 33060:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root' 
      MYSQL_DATABASE: 'configdb'