version: '2'
services: 
  redis:
    image: redis:latest
    command: redis-server --requirepass redis --appendonly yes
    container_name: redis
    ports:
       - "6379:6379"

    volumes:
      - ./data:/data
